name: Swisspower Dyn Preis Installer
slug: swisspower_dyn_preis_installer
description: Installiert die Swisspower Dyn Preis Custom Integration in /config/custom_components.
version: "0.1.0"
url: "https://github.com/EWHGOF/SwisspowerDynPreis"
arch:
  - aarch64
  - amd64
  - armv7
  - armhf
  - i386
startup: once
boot: auto
map:
  - config:rw
options: {}
schema: {}
